# meson.options
option(
  'extra_include',
  type : 'string',
  value : '',
  description : 'Path prefix for extra include directories (e.g. Android headers)'
)

option(
  'enable_intel',
  type : 'boolean',
  value : true,
  description : 'Enable Intel i915/xe driver build flags'
)

option(
  'enable_meson',
  type : 'boolean',
  value : true,
  description : 'Enable Amlogic Meson driver build flags'
)

option(
  'enable_msm',
  type : 'boolean',
  value : true,
  description : 'Enable Qualcomm MSM driver build flags'
)

option(
  'enable_arcvm',
  type : 'boolean',
  value : true,
  description : 'Enable ARCVM virtio‑gpu‑next driver build flags'
)
