option('drivers',
  type: 'array',
  choices: [
    'amdgpu', 'i915', 'xe', 'meson', 'msm', 'vc4',
    'mediatek', 'rockchip', 'virtgpu', 'radeon'
  ],
  description: 'List of GPU backends to build'
)

option(
  'ndk_include',
  type : 'string',
  value : '',
  description : 'Path prefix for extra include directories (e.g. Android headers)'
)

option(
  'extra_include',
  type : 'string',
  value : '',
  description : 'Path prefix for extra include directories (e.g. Android headers)'
)
